apiVersion: v1
kind: Secret
metadata:
  name: kargo-poc-repo
  namespace: kargo-poc
  labels:
    kargo.akuity.io/cred-type: git
type: Opaque
stringData:
  repoURL: https://github.com/asd99557/kargo-poc.git
  username: asd99557
  password: YOUR_GITHUB_PAT
