apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: myapp
  namespace: kargo-poc
spec:
  subscriptions:
    - image:
        repoURL: public.ecr.aws/nginx/nginx
        constraint: ^1.29.0
        discoveryLimit: 5
