apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kargo-poc
  namespace: kargo-poc
spec:
  promotionPolicies:
    - stageSelector:
        name: dev
      autoPromotionEnabled: true

    - stageSelector:
        name: qa
      autoPromotionEnabled: true

    - stageSelector:
        name: prod
      autoPromotionEnabled: true
