apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask

metadata:
  name: myapp-promotion
  namespace: kargo-poc

spec:
  vars:
    - name: gitopsRepo
      value: https://github.com/asd99557/kargo-poc.git

  steps:

    # 1. Checkout the exact Git commit that belongs to the Freight.
    #    Also checkout the target environment branch.
    - uses: git-clone
      config:
        repoURL: ${{ vars.gitopsRepo }}
        checkout:

          # Source configuration from the Freight
          - commit: ${{ commitFrom(vars.gitopsRepo).ID }}
            path: ./src

          # Environment branch that Argo CD watches
          - branch: stage/${{ ctx.stage }}
            create: true
            path: ./out

    # 2. Clear the old contents of stage/<environment>.
    - uses: git-clear
      config:
        path: ./out

    # 3. Copy the application base configuration.
    - uses: copy
      config:
        inPath: ./src/base
        outPath: ./out/base

    # 4. Copy the environment-specific Kustomize configuration.
    #
    # This preserves:
    #   replicas
    #   image
    #   namespace
    #   other environment configuration
    #
    - uses: copy
      config:
        inPath: ./src/stages/${{ ctx.stage }}
        outPath: ./out/stages/${{ ctx.stage }}

    # 5. Commit the promoted configuration.
    - uses: git-commit
      as: commit
      config:
        path: ./out
        message: "Promote Git commit ${{ commitFrom(vars.gitopsRepo).ID }} to ${{ ctx.stage }}"

    # 6. Push the environment branch.
    - uses: git-push
      config:
        path: ./out

    # 7. Tell Argo CD about the new Git commit.
    - uses: argocd-update
      config:
        apps:
          - name: myapp-${{ ctx.stage }}
            sources:
              - repoURL: ${{ vars.gitopsRepo }}
                desiredRevision: ${{ task.outputs.commit.commit }}