apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: myapp
  namespace: kargo-poc
spec:
  freightCreationPolicy: Automatic
  interval: 1m
  subscriptions:
    - image:
        repoURL: docker.io/library/nginx
        constraint: ~1.30.0
        discoveryLimit: 10
        imageSelectionStrategy: SemVer
        strictSemvers: true  
