apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: myapp
  namespace: kargo-poc
spec:
  freightCreationPolicy: Automatic
  interval: 1m
  subscriptions:
# watch Docker image
    - image:
        repoURL: docker.io/library/nginx
        constraint: ">=1.30.0 <1.31.0"
        discoveryLimit: 10
        imageSelectionStrategy: SemVer
        strictSemvers: true  

    - git:
        repoURL: https://github.com/asd99557/kargo-poc.git
        branch: main
        commitSelectionStrategy: NewestFromBranch
        includePaths:
          - base/