apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: myapp
  namespace: kargo-poc

spec:
  freightCreationPolicy: Automatic

  interval: 1m

  subscriptions:

    # Watch container image
    - image:
        repoURL: public.ecr.aws/nginx/nginx
        discoveryLimit: 10
        imageSelectionStrategy: SemVer
        constraint: ">=1.30.0 <2.0.0"

    # Watch Git configuration
    - git:
        repoURL: https://github.com/asd99557/kargo-poc.git
        branch: main
        commitSelectionStrategy: NewestFromBranch
        includePaths:
          - base/
          - stages/